FROM alpine:latest

# Install packages
# apk add libgcc libstdc++ ripgrep is needed for the claude cli to work, but it is not included in the base image.
RUN apk update && apk add --no-cache \
    bash \
    curl \
    git \
    build-base \
    python3 \
    py3-pip \
    go \
    sudo \
    libgcc \
    libstdc++ \
    ripgrep \
    docker-cli \
    docker-cli-buildx

# Create non-root user with sudo access
RUN addgroup -S opencode && adduser -S opencode -G opencode \
    && echo "opencode ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Create docker group, add claude user to it for Docker-in-Docker access
RUN addgroup -S docker && addgroup opencode docker

# Create wrapper script
# It is typically to be used for the "make opencode" command in the Makefile.
RUN echo '#!/bin/bash' > /usr/local/bin/opencode_start && \
    echo 'export PATH="$HOME/.opencode/bin:$PATH"' >> /usr/local/bin/opencode_start && \
    echo 'exec opencode' >> /usr/local/bin/opencode_start && \
    chmod +x /usr/local/bin/opencode_start

# Set up working directory
WORKDIR /workspace

# Copy and set up entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Switch to non-root user
USER opencode

# Install CLI for the main user
RUN curl -fsSL https://opencode.ai/install | bash && \
    echo 'export PATH="$HOME/.opencode/bin:$PATH"' >> ~/.bashrc

# "curl -fsSL https://opencode.ai/install | bash" is installing the last version
# However in case of trouble, we could swithc down to a forced working version
# Also, autoupdate is disabled for now (@ostaquet 19-MAY-2026)
#RUN curl -fsSL https://opencode.ai/install | bash -s -- --version 1.14.48 && \
#    echo 'export PATH="$HOME/.opencode/bin:$PATH"' >> ~/.bashrc

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]
