name: ${PROJECT_NAME:-opencode-dev}

services:

  dev:
    build:
      context: .
      dockerfile: Dockerfile.opencode
    image: ${PROJECT_NAME:-opencode-dev}/opencode-dev
    container_name: ${PROJECT_NAME:-opencode-dev}-opencode-dev
    volumes:
      - ../..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - PROJECT_NAME=${PROJECT_NAME:-workspace}
      - OPENCODE_CONFIG_DIR=/workspace/.opencode/
    stdin_open: true
    tty: true
